# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
title: 'QSYS, INC.'
subtitle: '- Web & Database applications'
email: contact@quintsys.com
description: > # this means to ignore newlines until "baseurl:"
  Web & Database applications development. Online and data driven, secure and performant to meet your specifications.
baseurl: "" # the sub-path of your site, e.g. /blog
url: 'https://quintsys.github.io' # the base hostname & protocol for your site
twitter_username: quintsysinc
github_username:  quintsys

twitter_url: 'https://twitter.com/QuintSysInc'
github_url: 'https://github.com/QuintSys'
linkedin_url: 'https://www.linkedin.com/in/erich-quintero-5516075'
phone: '305.403.9582'

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Build settings
markdown: kramdown
sass:
  style: compressed
include: ['_pages']

#gems:
#  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

